[package]
name = "cybercipher-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CyberCipher desktop application (Tauri 2)"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64.workspace = true
cybercipher-core.workspace = true
cybercipher-codec.workspace = true
cybercipher-engine.workspace = true
cybercipher-attack.workspace = true
cybercipher-pki.workspace = true
cybercipher-sstv.workspace = true
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
parking_lot.workspace = true
