//! Integration tests for `cybercipher-pki` RSA key foundations: keygen,
//! PEM/DER round-trips, typed parse errors, JWK/JWKS conversion, and
//! inspection.

use cybercipher_core::{ErrorKind, OperationError};
use cybercipher_pki::{
    generate_rsa_keypair, inspect_der, inspect_pem, jwk_to_json, jwk_to_keypair,
    jwk_to_public_material, jwks_to_json, keypair_to_jwk, parse_jwk, parse_jwks, parse_pem,
    parse_pkcs1_private_der, parse_pkcs1_public_der, parse_pkcs8_private_der,
    parse_spki_public_der, public_material_to_jwk, InspectKey, KeyFormat, KeyType, ParsedKey,
    RsaJwk, RsaKeypair, DEFAULT_EXPONENT_HEX,
};
use rsa::Oaep;
use sha2::Sha256;

// ---------------------------------------------------------------------------
// Static fixture: an RSA-1024 key generated by this crate's own keygen, with
// its public SPKI PEM and modulus committed so inspection is deterministic.
// ---------------------------------------------------------------------------

const FIXTURE_SPKI_PEM: &str = "\
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqtktk5obf4BQxmJtI8mKd0m4/
bbwpCL+75wypHh/eTIyT53I2Mx66x5AqAzw0aIuPscoxDsh6dhDMpkqj8lWxocpa
ny5QFtkokwePPY883CXISHQj6IZ4CuiQGyKyDI0MeiYtw91gK/qWcRU0e6VJ8FJy
dF9To/zdyf2+9OyYTwIDAQAB
-----END PUBLIC KEY-----
";

const FIXTURE_N_HEX: &str = "aab64b64e686dfe01431989b48f2629dd26e3f6dbc2908bfbbe70ca91e1fde4c8c93e77236331ebac7902a033c34688b8fb1ca310ec87a7610cca64aa3f255b1a1ca5a9f2e5016d92893078f3d8f3cdc25c8487423e886780ae8901b22b20c8d0c7a262dc3dd602bfa967115347ba549f05272745f53a3fcddc9fdbef4ec984f";
const FIXTURE_E_HEX: &str = "010001";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn gen(bits: usize) -> RsaKeypair {
    generate_rsa_keypair(bits, DEFAULT_EXPONENT_HEX).expect("keygen should succeed")
}

/// A syntactically valid PEM block with a valid-base64 but meaningless body.
fn pem_with_body(label: &str, body: &str) -> String {
    format!("-----BEGIN {label}-----\n{body}\n-----END {label}-----\n")
}

fn assert_kind(err: &OperationError, kind: ErrorKind) {
    assert_eq!(err.kind, kind, "unexpected error: {err}");
}

// ---------------------------------------------------------------------------
// Key generation
// ---------------------------------------------------------------------------

#[test]
fn keygen_2048_material_and_oaep_roundtrip() {
    let keypair = gen(2048);
    let m = keypair.material();

    // Modulus size and default exponent.
    assert_eq!(keypair.bits(), 2048);
    assert_eq!(m.e, DEFAULT_EXPONENT_HEX);
    assert_eq!(m.e, "010001");
    // Hex transport: even-length lowercase hex, n is 2048 bits = 512 nibbles.
    assert_eq!(m.n.len(), 512);
    assert!(m.n.bytes().all(|b| b.is_ascii_hexdigit()));
    // All eight components present and distinct where they must be.
    for (name, value) in [
        ("n", &m.n),
        ("e", &m.e),
        ("d", &m.d),
        ("p", &m.p),
        ("q", &m.q),
        ("dp", &m.dp),
        ("dq", &m.dq),
        ("qinv", &m.qinv),
    ] {
        assert!(!value.is_empty(), "{name} missing");
    }
    assert_ne!(m.p, m.q, "p and q must differ");

    // Sanity: the rsa crate's own OAEP survives one encrypt/decrypt round
    // using the key material this crate produced.
    let plaintext = b"cybercipher oaep sanity";
    let private = keypair.rsa_private_key();
    let public = keypair.rsa_public_key();
    let ciphertext = public
        .encrypt(&mut rand::rngs::OsRng, Oaep::new::<Sha256>(), plaintext)
        .expect("OAEP encrypt");
    let recovered = private
        .decrypt(Oaep::new::<Sha256>(), &ciphertext)
        .expect("OAEP decrypt");
    assert_eq!(recovered, plaintext);

    // PKCS#8 PEM round-trip: serialize, re-parse, all fields must match.
    let pkcs8_pem = keypair.to_pkcs8_pem().expect("pkcs8 pem");
    assert!(pkcs8_pem.starts_with("-----BEGIN PRIVATE KEY-----"));
    let reparsed = match parse_pem(&pkcs8_pem).expect("re-parse pkcs8") {
        ParsedKey::Private { keypair, format } => {
            assert_eq!(format, KeyFormat::Pkcs8);
            keypair
        }
        _ => panic!("expected a private key"),
    };
    assert_eq!(reparsed.material(), m);
    assert_eq!(reparsed.bits(), 2048);
}

#[test]
fn keygen_1024_is_labeled_legacy() {
    let keypair = gen(1024);
    let inspection = keypair.inspect().unwrap();
    assert_eq!(inspection.bit_length, 1024);
    assert!(
        inspection.summary.contains("legacy"),
        "summary: {}",
        inspection.summary
    );
    assert!(
        inspection.strength.contains("deprecated"),
        "strength: {}",
        inspection.strength
    );
}

#[test]
fn keygen_rejects_unsupported_bit_lengths() {
    // Below the floor.
    let err = generate_rsa_keypair(100, DEFAULT_EXPONENT_HEX).unwrap_err();
    assert_kind(&err, ErrorKind::InvalidParam);
    assert_eq!(err.parameter.as_deref(), Some("bits"));

    // Above the cap — the error points at the cap and at the attack tooling.
    let err = generate_rsa_keypair(8192, DEFAULT_EXPONENT_HEX).unwrap_err();
    assert_kind(&err, ErrorKind::InvalidParam);
    assert!(err.message.contains("4096"), "message: {}", err.message);
    assert!(err
        .details
        .as_deref()
        .unwrap_or_default()
        .contains("attack"));

    // In-between sizes are rejected too (not silently rounded).
    for bits in [1500usize, 2049, 3] {
        let err = generate_rsa_keypair(bits, DEFAULT_EXPONENT_HEX).unwrap_err();
        assert_kind(&err, ErrorKind::InvalidParam);
    }
}

#[test]
fn keygen_rejects_bad_exponents() {
    // Not hex.
    let err = generate_rsa_keypair(2048, "zzzz").unwrap_err();
    assert_kind(&err, ErrorKind::Decode);
    assert_eq!(err.parameter.as_deref(), Some("e"));

    // Even exponent.
    let err = generate_rsa_keypair(2048, "010000").unwrap_err();
    assert_kind(&err, ErrorKind::InvalidParam);
    assert!(err.message.contains("odd"), "message: {}", err.message);

    // Too small (1 and 2).
    for e in ["01", "02"] {
        let err = generate_rsa_keypair(2048, e).unwrap_err();
        assert_kind(&err, ErrorKind::InvalidParam);
        assert!(err.message.contains(">= 3"), "message: {}", err.message);
    }
}

// ---------------------------------------------------------------------------
// PEM container recognition
// ---------------------------------------------------------------------------

#[test]
fn all_four_pem_headers_parse_with_correct_format() {
    let keypair = gen(2048);

    let cases = [
        (
            keypair.to_public_spki_pem().unwrap(),
            KeyFormat::Spki,
            KeyType::RsaPublic,
        ),
        (
            keypair.to_public_pkcs1_pem().unwrap(),
            KeyFormat::Pkcs1,
            KeyType::RsaPublic,
        ),
        (
            keypair.to_pkcs8_pem().unwrap(),
            KeyFormat::Pkcs8,
            KeyType::RsaPrivate,
        ),
        (
            keypair.to_pkcs1_pem().unwrap(),
            KeyFormat::Pkcs1,
            KeyType::RsaPrivate,
        ),
    ];
    for (pem, format, key_type) in cases {
        let inspection = inspect_pem(&pem).expect("parse should succeed");
        assert_eq!(inspection.format, format, "pem: {pem}");
        assert_eq!(inspection.key_type, key_type);
    }

    // Public PEMs parse to public material whose n/e match the keypair.
    let public_pem = keypair.to_public_spki_pem().unwrap();
    match parse_pem(&public_pem).expect("parse public") {
        ParsedKey::Public { material, format } => {
            assert_eq!(format, KeyFormat::Spki);
            assert_eq!(material, keypair.public_material());
        }
        _ => panic!("expected a public key"),
    }
}

#[test]
fn serialize_every_direction_from_a_parsed_key() {
    let original = gen(2048);
    // Parse once from PKCS#8 and regenerate all four PEM forms from the
    // parsed key; each must parse again with identical material.
    let pkcs8_pem = original.to_pkcs8_pem().unwrap();
    let parsed = match parse_pem(&pkcs8_pem).unwrap() {
        ParsedKey::Private { keypair, .. } => keypair,
        _ => panic!("expected private"),
    };
    let m = original.material();

    for pem in [
        parsed.to_pkcs8_pem().unwrap(),
        parsed.to_pkcs1_pem().unwrap(),
        parsed.to_public_spki_pem().unwrap(),
        parsed.to_public_pkcs1_pem().unwrap(),
    ] {
        let inspection = inspect_pem(&pem).unwrap();
        assert_eq!(inspection.n, m.n);
        assert_eq!(inspection.e, m.e);
    }

    // Same for a public-only key: both public PEM forms.
    let public_pem = original.to_public_spki_pem().unwrap();
    match parse_pem(&public_pem).unwrap() {
        ParsedKey::Public { material, .. } => {
            // Re-serialization is deterministic: identical PEM.
            assert_eq!(material.to_spki_pem().unwrap(), public_pem);
            assert!(material
                .to_pkcs1_pem()
                .unwrap()
                .starts_with("-----BEGIN RSA PUBLIC KEY-----"));
        }
        _ => panic!("expected public"),
    }
}

#[test]
fn certificate_pem_is_a_typed_wrong_object_type_error() {
    // Valid base64 body so only the label classification is exercised.
    let pem = pem_with_body("CERTIFICATE", "MIIB");
    let err = parse_pem(&pem).unwrap_err();
    assert_kind(&err, ErrorKind::InvalidInput);
    assert!(
        err.message.contains("wrong PEM object type"),
        "message: {}",
        err.message
    );
    assert_eq!(err.actual.as_deref(), Some("CERTIFICATE"));
    assert!(err
        .details
        .as_deref()
        .unwrap_or_default()
        .contains("certificate"));

    // Same classification for CSRs and CRLs.
    for label in ["CERTIFICATE REQUEST", "X509 CRL"] {
        let err = parse_pem(&pem_with_body(label, "MIIB")).unwrap_err();
        assert_kind(&err, ErrorKind::InvalidInput);
    }
}

#[test]
fn garbage_pem_body_is_a_typed_decode_error() {
    // Valid armor, valid base64, invalid DER.
    let pem = pem_with_body("PUBLIC KEY", "AAAA");
    let err = parse_pem(&pem).unwrap_err();
    assert_kind(&err, ErrorKind::Decode);
    assert!(
        err.message.contains("invalid DER"),
        "message: {}",
        err.message
    );
    assert!(err.details.is_some(), "DER parser detail expected");

    // Valid armor, non-base64 body.
    let pem = pem_with_body("RSA PRIVATE KEY", "!!! not base64 !!!");
    let err = parse_pem(&pem).unwrap_err();
    assert_kind(&err, ErrorKind::Decode);

    // Completely missing armor.
    let err = parse_pem("just some text").unwrap_err();
    assert_kind(&err, ErrorKind::Decode);

    // Missing END marker.
    let pem = "-----BEGIN PUBLIC KEY-----\nAAAA\n";
    let err = parse_pem(pem).unwrap_err();
    assert_kind(&err, ErrorKind::Decode);

    // Empty input.
    let err = parse_pem("   \n  ").unwrap_err();
    assert_kind(&err, ErrorKind::Decode);
}

#[test]
fn encrypted_pem_is_rejected_with_clear_not_supported_error() {
    // Modern PKCS#8 encrypted label.
    let pem = pem_with_body("ENCRYPTED PRIVATE KEY", "MIIB");
    let err = parse_pem(&pem).unwrap_err();
    assert_kind(&err, ErrorKind::Unsupported);
    assert!(
        err.message.contains("encrypted keys are not supported yet"),
        "message: {}",
        err.message
    );

    // Legacy RFC 1421 headers on a PKCS#1 private key.
    let pem = "-----BEGIN RSA PRIVATE KEY-----\n\
               Proc-Type: 4,ENCRYPTED\n\
               DEK-Info: DES-EDE3-CBC,A1B2C3D4E5F60718\n\n\
               MIIB\n\
               -----END RSA PRIVATE KEY-----\n";
    let err = parse_pem(pem).unwrap_err();
    assert_kind(&err, ErrorKind::Unsupported);
    assert!(
        err.message.contains("not supported yet"),
        "message: {}",
        err.message
    );
}

#[test]
fn unknown_pem_label_is_typed_unsupported() {
    let pem = pem_with_body("OPENSSH PRIVATE KEY", "b3BlbnNzaC1rZXktdjEAAAAA");
    let err = parse_pem(&pem).unwrap_err();
    assert_eq!(err.kind, ErrorKind::Unsupported);
    assert!(
        err.message.contains("OPENSSH PRIVATE KEY"),
        "message: {}",
        err.message
    );
}

#[test]
fn unsupported_algorithm_oid_is_typed() {
    // A well-formed PKCS#8 PrivateKeyInfo carrying an EC key OID
    // (id-ecPublicKey 1.2.840.10045.2.1) instead of rsaEncryption.
    let ec_pkcs8: &[u8] = &[
        0x30, 0x10, // SEQUENCE (16 content bytes)
        0x02, 0x01, 0x00, // version INTEGER 0
        0x30, 0x09, // AlgorithmIdentifier SEQUENCE (9 content bytes, no params)
        0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01, // OID ecPublicKey
        0x04, 0x00, // privateKey OCTET STRING (empty)
    ];
    let err = parse_pkcs8_private_der(ec_pkcs8).unwrap_err();
    assert_kind(&err, ErrorKind::Unsupported);
    assert!(
        err.message.contains("rsaEncryption"),
        "message: {}",
        err.message
    );

    // SPKI carrying the same non-RSA OID.
    let ec_spki: &[u8] = &[
        0x30, 0x0f, // SEQUENCE (15 bytes)
        0x30, 0x09, // AlgorithmIdentifier SEQUENCE (9 bytes)
        0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01, // OID ecPublicKey
        0x03, 0x02, 0x00, 0xaa, // subjectPublicKey BIT STRING
    ];
    let err = parse_spki_public_der(ec_spki).unwrap_err();
    assert_kind(&err, ErrorKind::Unsupported);
}

// ---------------------------------------------------------------------------
// DER raw-object round-trips
// ---------------------------------------------------------------------------

#[test]
fn der_roundtrip_all_four_structures() {
    let keypair = gen(2048);
    let m = keypair.material();
    let pub_m = keypair.public_material();

    // Private: PKCS#1 and PKCS#8.
    let pkcs1 = keypair.to_pkcs1_der().unwrap();
    assert_eq!(parse_pkcs1_private_der(&pkcs1).unwrap().material(), m);
    let pkcs8 = keypair.to_pkcs8_der().unwrap();
    assert_eq!(parse_pkcs8_private_der(&pkcs8).unwrap().material(), m);

    // Public: PKCS#1 and SPKI.
    let pub_pkcs1 = keypair.to_public_pkcs1_der().unwrap();
    assert_eq!(parse_pkcs1_public_der(&pub_pkcs1).unwrap(), pub_m);
    let spki = keypair.to_public_spki_der().unwrap();
    assert_eq!(parse_spki_public_der(&spki).unwrap(), pub_m);

    // inspect_der sniffs each structure and reports its format.
    assert_eq!(inspect_der(&pkcs8).unwrap().format, KeyFormat::Pkcs8);
    assert_eq!(inspect_der(&pkcs1).unwrap().format, KeyFormat::Pkcs1);
    assert_eq!(inspect_der(&spki).unwrap().format, KeyFormat::Spki);
    assert_eq!(inspect_der(&pub_pkcs1).unwrap().format, KeyFormat::Pkcs1);

    // Garbage DER is a typed decode error, not a panic.
    let err = inspect_der(&[0x00, 0x01, 0x02, 0x03]).unwrap_err();
    assert_kind(&err, ErrorKind::Decode);
}

// ---------------------------------------------------------------------------
// JWK / JWKS
// ---------------------------------------------------------------------------

#[test]
fn jwk_roundtrip_key_to_json_and_back() {
    let keypair = gen(2048);
    let m = keypair.material();

    let jwk = keypair_to_jwk(&keypair);
    assert_eq!(jwk.kty, "RSA");
    // Private JWK carries the full parameter set.
    assert!(jwk.d.is_some() && jwk.p.is_some() && jwk.q.is_some());
    assert!(jwk.dp.is_some() && jwk.dq.is_some() && jwk.qi.is_some());
    // base64url without padding.
    assert!(!jwk.n.contains('=') && !jwk.n.contains('+') && !jwk.n.contains('/'));

    let json = jwk_to_json(&jwk).unwrap();
    let parsed = parse_jwk(&json).unwrap();
    assert_eq!(parsed, jwk);

    let back = jwk_to_keypair(&parsed).unwrap();
    assert_eq!(back.material(), m);

    // Public-only direction.
    let public_jwk = public_material_to_jwk(&keypair.public_material());
    assert!(public_jwk.d.is_none());
    let public_back = jwk_to_public_material(&public_jwk).unwrap();
    assert_eq!(public_back, keypair.public_material());
}

#[test]
fn jwk_with_missing_crt_params_still_loads() {
    // RFC 7518 section 6.3.2: dp/dq/qi are optional. Start from a full JWK,
    // strip the CRT parameters, and the key must still reconstruct.
    let keypair = gen(2048);
    let mut jwk = keypair_to_jwk(&keypair);
    jwk.dp = None;
    jwk.dq = None;
    jwk.qi = None;
    let back = jwk_to_keypair(&jwk).unwrap();
    let m = back.material();
    // n/e/d/p/q preserved; dp/dq/qinv re-derived identically.
    assert_eq!(m.n, keypair.material().n);
    assert_eq!(m.d, keypair.material().d);
    assert_eq!(m.dp, keypair.material().dp);
    assert_eq!(m.qinv, keypair.material().qinv);
}

#[test]
fn jwk_errors_are_typed() {
    // Wrong kty: the kty check fires before any parameter decoding, so an
    // EC-typed JWK with empty parameters still gets the typed error.
    let ec_jwk = RsaJwk {
        kty: "EC".to_string(),
        n: String::new(),
        e: String::new(),
        d: None,
        p: None,
        q: None,
        dp: None,
        dq: None,
        qi: None,
        kid: None,
    };
    let err = jwk_to_public_material(&ec_jwk).unwrap_err();
    assert_eq!(err.kind, ErrorKind::Unsupported);
    assert!(err.message.contains("kty"), "message: {}", err.message);

    // Bad base64url in n.
    let keypair = gen(2048);
    let mut jwk = keypair_to_jwk(&keypair);
    jwk.n = "%%%".to_string();
    let err = jwk_to_keypair(&jwk).unwrap_err();
    assert_kind(&err, ErrorKind::Decode);
    assert_eq!(err.parameter.as_deref(), Some("n"));

    // Public JWK used where a private key is needed.
    let public_jwk = public_material_to_jwk(&keypair.public_material());
    let err = jwk_to_keypair(&public_jwk).unwrap_err();
    assert_eq!(err.kind, ErrorKind::InvalidInput);

    // Private JWK without p/q: not supported yet (no factoring).
    let mut private_no_p = keypair_to_jwk(&keypair);
    private_no_p.p = None;
    private_no_p.q = None;
    let err = jwk_to_keypair(&private_no_p).unwrap_err();
    assert_eq!(err.kind, ErrorKind::Unsupported);
    assert!(
        err.message.contains("not supported yet"),
        "message: {}",
        err.message
    );

    // Invalid JSON.
    let err = parse_jwk("{not json").unwrap_err();
    assert_kind(&err, ErrorKind::Decode);
}

#[test]
fn jwks_parse_object_and_bare_array() {
    let keypair = gen(2048);
    let jwk = keypair_to_jwk(&keypair);
    let json = jwk_to_json(&jwk).unwrap();

    // RFC 7517 section 5 object form.
    let jwks = format!(r#"{{"keys": [{json}]}}"#);
    let keys = parse_jwks(&jwks).unwrap();
    assert_eq!(keys.len(), 1);
    assert_eq!(keys[0], jwk);

    // Bare array form.
    let bare = format!("[{json}]");
    let keys = parse_jwks(&bare).unwrap();
    assert_eq!(keys.len(), 1);

    // Round-trip through jwks_to_json.
    let serialized = jwks_to_json(&keys).unwrap();
    assert_eq!(parse_jwks(&serialized).unwrap(), keys);

    // Neither form -> typed decode error.
    let err = parse_jwks("{\"nope\": []}").unwrap_err();
    assert_kind(&err, ErrorKind::Decode);
}

#[test]
fn jwk_inspection_reports_jwk_format_and_hex() {
    let keypair = gen(2048);
    let jwk = keypair_to_jwk(&keypair);
    let inspection = jwk.inspect().unwrap();
    assert_eq!(inspection.format, KeyFormat::Jwk);
    assert_eq!(inspection.key_type, KeyType::RsaPrivate);
    assert_eq!(inspection.bit_length, 2048);
    assert_eq!(inspection.n, keypair.material().n);
    assert!(inspection.qinv.is_some());

    let public = public_material_to_jwk(&keypair.public_material());
    let inspection = public.inspect().unwrap();
    assert_eq!(inspection.key_type, KeyType::RsaPublic);
    assert!(inspection.d.is_none());
}

// ---------------------------------------------------------------------------
// Static fixture
// ---------------------------------------------------------------------------

#[test]
fn committed_fixture_public_key_matches_recorded_material() {
    let inspection = inspect_pem(FIXTURE_SPKI_PEM).unwrap();
    assert_eq!(inspection.format, KeyFormat::Spki);
    assert_eq!(inspection.key_type, KeyType::RsaPublic);
    assert_eq!(inspection.bit_length, 1024);
    assert_eq!(inspection.n, FIXTURE_N_HEX);
    assert_eq!(inspection.e, FIXTURE_E_HEX);
    assert!(
        inspection.d.is_none(),
        "public key must not leak private fields"
    );
    assert!(
        inspection.summary.contains("1024"),
        "summary: {}",
        inspection.summary
    );
}

// ---------------------------------------------------------------------------
// Inspection & serde shape
// ---------------------------------------------------------------------------

#[test]
fn inspection_serializes_snake_case_with_private_fields() {
    let keypair = gen(2048);
    let inspection = keypair.inspect().unwrap();
    let json = serde_json::to_string(&inspection).unwrap();
    assert!(
        json.contains("\"key_type\":\"rsa_private\""),
        "json: {json}"
    );
    assert!(json.contains("\"bit_length\":2048"), "json: {json}");
    assert!(json.contains("\"qinv\""), "json: {json}");
    assert!(json.contains("\"summary\""), "json: {json}");

    // Public inspection omits private fields entirely.
    let public = keypair.public_material();
    let json = serde_json::to_string(&public.inspect().unwrap()).unwrap();
    assert!(
        !json.contains("\"d\""),
        "public inspection must omit d: {json}"
    );
}

#[test]
fn key_material_serializes_as_flat_hex_object() {
    let keypair = gen(2048);
    let json = serde_json::to_string(&keypair.material()).unwrap();
    for field in ["n", "e", "d", "p", "q", "dp", "dq", "qinv"] {
        assert!(
            json.contains(&format!("\"{field}\"")),
            "missing {field}: {json}"
        );
    }
    // Values are hex strings, not numbers.
    let value: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert!(value["n"].is_string());
}
